### ISSUE TITLE
一个协程继承对象导致语法提示出现错误

### ISSUE THREAD

**Issue by GeniusLe** [wudi/swoole-ide-helper#103]
[https://github.com/wudi/swoole-ide-helper/blob/fceabb51fca645166fdc3d885bb582eb3352335e/src/Coroutine/MySQL.php#L19](url)
[https://github.com/bmewburn/vscode-intelephense/issues/740](url)
请参见上方的2个地址

**Comment by wudi** [comment]
Thanks for feedback, i had fixed in commit a255daa05feffbf4b88d59897a9470696d2fe259
Please use `composer update eaglewu/swoole-ide-helper` to update it.
