### ISSUE TITLE
Any luck with english docs?

### ISSUE THREAD

**Issue by valVk** [wudi/swoole-ide-helper#74]
Now IDE helper is  supporting non-english phpdocs and API reference, any luck with translations? (

**Comment by eaglewu** [comment]
Thanks for your feedback.
I had checkout new branch `english`. I will update in english docs on the branch.
Welcome PRs for helper improvement the docs.

**Comment by eaglewu** [comment]
For english docs you can also follow official references http://php.net/manual/en/book.swoole.php

**Comment by valVk** [comment]
Thanks!

**Comment by osrec** [comment]
Let us know if you need any help with English documentation - members of OSREC Tech will be more than happy to help out!

**Comment by paveljanda** [comment]
👍
