### ISSUE TITLE
Can i use this with VS Code on Windows? :)

### ISSUE THREAD

**Issue by flddr** [wudi/swoole-ide-helper#76]
I have no idea how to.

Please help :)

**Comment by wudi** [comment]
Yes, please following  below.

### 1. Use Composer package manager
 just use `composer require --dev eaglewu/swoole-ide-helper:dev-master` it will download repo in vendor directory for VS Code index.

### 2. No Composer
you need clone/download the repo in your workspace

(PS: recommend PHPStorm IDE)

**Comment by flddr** [comment]
Sorry, thanks for your help. My time with PHP is a decade ago and i have never used composer.

Actually, for development i am running vs code on windows 10 and swoole via bash linking from ubuntu 18.04 in WSL. Dont know if this works for IDE Helper?

So, i tried both and got a composer.json and a vendor folder - but i do absolutely not understand how to use them. Thats all in all confusing :)

Maybe, you can help me a bit more 👍

**Comment by flddr** [comment]
Thank you for your help 👍 

I do not understand how to use it 😕 

Actually

![image](https://user-images.githubusercontent.com/42785945/46434278-84dba400-c753-11e8-822a-6e28b356ed3d.png)

I tried different things, but nothing works 😕

**Comment by flddr** [comment]
My Intellisense (php autocomplete) was broken 😄

thanks for this great tool 💯
