### ISSUE TITLE
Missing method declarations, old class names

### ISSUE THREAD

**Issue by paveljanda** [wudi/swoole-ide-helper#78]
Hello,

in latest version, there is no class called `Mysql` but `MySQL`. Also there is missing method declaration of `Swoole\Redis::publish()`.

Could you add it please? :)

**Comment by paveljanda** [comment]
@wudi thank you.

To the Redis issue: Swoole\Redis implements all redis methods, right? Like get, set, hget, hgetall, .... (https://redis.io/commands).

**Comment by paveljanda** [comment]
Btw, https://www.swoole.co.uk/docs/modules/swoole-async-redis-client ->
`Swoole\Redis::subscribe`, `Swoole\Redis::unsubscribe`, ...

**Comment by wudi** [comment]
https://github.com/swoole/swoole-src/blob/master/swoole_redis.c#L465
I saw implements of Swoole\Redis is via `__call` method.
So do it 957127e

**Comment by paveljanda** [comment]
Ir sure do. But noone knows what that method should return and what arguments should be passed to the client method. :D I think it would be awesome to genereta the docs with a annotation like here: https://github.com/nrk/predis/blob/v1.1/src/ClientInterface.php What do you think?

**Comment by wudi** [comment]
Done 96d3fa5

**Notice**: return params is fixed bool for these annotations. Depend on `__call` method.

If u have any other ideas. PR it.

TKS

**Comment by paveljanda** [comment]
Thank you. 👍 

I will. :)
