### ISSUE TITLE
缺少构造函数文档

### ISSUE THREAD

**Issue by wi1dcard** [wudi/swoole-ide-helper#83]
对比：

<https://github.com/wudi/swoole-ide-helper/blob/master/src/Coroutine/Client.php>

<https://github.com/swoole/ide-helper/blob/master/output/namespace/Coroutine/Client.php>

缺少：

<https://github.com/swoole/ide-helper/blob/fac19b41628c9b0c3423c3832f2eb070e4628bff/output/namespace/Coroutine/Client.php#L17-L21>

**Comment by wudi** [comment]
Fix b4c3b76977bc245010eeef1517017131200d983f

可以直接提交 PR :)

**Comment by wi1dcard** [comment]
@wudi Thanks，下午比较忙，所以没来得及提交 PR。
