### ISSUE TITLE
Co::suspend has parameter?

### ISSUE THREAD

**Issue by crazywhalecc** [wudi/swoole-ide-helper#87]
Co::suspend();
helper里面是带一个必需的参数co_id的，但是swoole官方文档中没有说要用参数。且官方文档中有yield()关键字，helper里没有（还有getCid()也没有好像）

**Comment by wudi** [comment]
https://github.com/swoole/swoole-src/blob/d0d30a3e4c3c38ed647cf8dad0b01c123306962f/examples/coroutine/coro_util.php#L7

老版本兼容问题
