### ISSUE TITLE
跟随 Swoole 版本的分支和发布机制

### ISSUE THREAD

**Issue by g5li** [wudi/swoole-ide-helper#93]
Swoole 4.x 的开发很活跃，一些 函数的定义也有变化的可能。现在此项目只有 **master** 分支，所有的 PL 都被合并到这各分支中。

建议维护 **4.0**, **4.1**, **4.2** 三个分支，提交 PL 时，需要声明 PL 确认合并到到哪个分支。

如果维护 三个分支有压力，也可以只建立 4.x 的分支，通过 phpDoc 的 since 和 deprecated 来声明函数说明的可用性。

**Comment by wudi** [comment]
暂时不考虑该特性，推荐采用块注释中 **since** 特性
例如：
```php
/**
 * Returns the last error occurred
 * @return int an integer, the value can be one of the following
 * constants:
 * @since 5.6.0
 */
public function Foo() {
}
```
